### ISSUE TITLE
[Bug]: Progress was not saved

### ISSUE THREAD

**Issue by 0verEngineer** [advplyr/audiobookshelf#1660]
### Describe the issue

I use the app and the web-ui. Yesterday i listened about 2 hours on the web-ui and continued today on the app and the progress from the web-ui from the day before was not used/saved/whatever... it started where i stopped on the app and not on the web-ui where i made progress.

I have this audiobook downloaded in the app.

### Steps to reproduce the issue

1. Listen on mobile app and pause
2. Switch to web-ui, listen, then pause
3. Switch back to the mobile app and progress from web-ui is not synced

However i cannot reproduce it when i try, but this has happened twice to me.

### Audiobookshelf version

v2.2.17

### How are you running audiobookshelf?

Docker

Browser was Firefox

**Comment by Commiccannon** [comment]
I have had the same issue, on the web version getting popup error. Link to that issue https://github.com/advplyr/audiobookshelf-app/issues/671

**Comment by 0verEngineer** [comment]
Yea it happened to me yesterday again, listened on the web ui, paused and opened the app, opened the audiobook and the progress percentage was right but the progess time was wrong, i clicked play and it continued with the wrong progress time from the app and then the percentage changed to match the wrong progress time from the app.

So this looks like the app fetches the right time and progress but fails to use it.

**Comment by Commiccannon** [comment]
Do you get a red popup message on the web player saying Progress is not being synced. Restart playback?

**Comment by 0verEngineer** [comment]
> Do you get a red popup message on the web player saying Progress is not being synced. Restart playback?
> 

The last time i got one but that did not help, it was also wrong after playback restart if i recall correctly. But this time there was no popup

**Comment by 0verEngineer** [comment]
It did happen for me twice this day, in the app and in the web-ui.

Web-UI:
I had my browser in the backgroud with the web-ui running and when i clicked play it seemed that it just started playing where it was left off without querying the server for the progress

App:
I stopped listening in the web-ui and opened the app, (was open in the background the whole time i think) i pressed the play button and it started playing where it was left off in the app, just like the web-ui it seems that it does start playing without contacting the server for the progress

**Comment by advplyr** [comment]
I made an update that will help to handle when multiple sessions are open for the same media item.

If you have the same media item open and playing then an alert will appear letting you know that this is happening. This would be user error since playing both at the same time would have colliding progress updates.

The more common case, which is the one you are referring to, is when you leave the player open and paused on one device. In this case the open and paused player will update its current time as progress is updated on another device.

Just to break that down a bit more here is the example:
1. You listen on the web ui then pause leaving the audio player open.
2. On your mobile device you start listening to the same media item.
3. The audio player in the web ui should update its time automatically as your mobile device reports its progress.

**Comment by advplyr** [comment]
Fixed in [v2.2.21](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.21)

**Comment by 0verEngineer** [comment]
@advplyr I think there is still an issue if the audiobooks are downloaded in the mobile app, i lost my progress twice yesterday, this was on v2.2.23

**Comment by 0verEngineer** [comment]
@advplyr I listened to the audiobook i have downloaded on my pc, then paused and started the mobile app, it has shown me the correct percentage exactly where i paused on the pc but it started playing where i stopped in the app, this means it has the progress in the app but it ignores it. Then the wrong progress is immediately synced to the website opened on the pc so that the progress is lost there as well.

**Comment by 0verEngineer** [comment]
@advplyr Can you please reopen this issue, or should i create a new one?
