### ISSUE TITLE
[Bug]: Bulk Quick Match with "Update Details" leaves empty series

### ISSUE THREAD

**Issue by amasover** [advplyr/audiobookshelf#2290]
### Describe the issue

When initially scanning a library, series will automatically be created based on folder structure. If you then later do a quick match on all items in a series when "prefer matched metadata" is selected, the series metadata will be overwritten with the series name from the metadata provider. However, the old folder-based series will sometimes not be removed, and will show up as a series with zero items in it.

In this screenshot for some reason I did not encounter this issue with Culture, but I did with The Witcher.

![image](https://github.com/advplyr/audiobookshelf/assets/484819/1e2d8ee6-3b13-496f-8217-a806ca3d57d6)

### Steps to reproduce the issue

1. Scan a library that contains a series folder structure
2. Enable "prefer matched metadata"
3. Quick match the library

### Audiobookshelf version

v2.5.0

### How are you running audiobookshelf?

Docker

**Comment by kieraneglin** [comment]
I couldn't figure out how to remove empty series, but I did find that you can go into the new series -> edit one book to be in the old series -> manually run a match on that book. That should move it back to the new series AND delete the empty old series

**Comment by amasover** [comment]
I can confirm that in the latest version (v2.7.2), I no longer see this issue.

**Comment by HikariNoKitsune** [comment]
Am currently on v2.7.2, and I have this exact same issue. Nothing I have done is working to remove this empty series.

![image](https://github.com/advplyr/audiobookshelf/assets/10123174/7c49e05e-e2f7-4d92-8351-8a95feae7f83)

Other than this issue, and a few other quirks, this project has been quite nice to work with and setup. My brother wanted to listen to some books that I had from ages ago, and they wanted to share some with me, so this is letting us 'trade books' with each other in a nicely organized manner :D Thank you all for having made such an easy to set up self hosting project!

**Comment by nyhil116** [comment]
I can confirm that in Audiobookshelf v2.10.1 this is still an issue.

![ABS_EmptySeries](https://github.com/advplyr/audiobookshelf/assets/125940376/8c2f262c-4875-4317-a7c6-1d6b1f579b2c)

**Comment by nichwall** [comment]
> I can confirm that in Audiobookshelf v2.10.1 this is still an issue.
> 
> ![ABS_EmptySeries](https://github.com/advplyr/audiobookshelf/assets/125940376/8c2f262c-4875-4317-a7c6-1d6b1f579b2c)
> 

Is this with a new install or upgrading from an old version? You can add a book to the series, same, then remove the book from the series to force the deletion of the old series.

**Comment by nyhil116** [comment]
It was installed recently (within the last month or so), I don't remember if I upgraded it though sadly. It's installed via docker on Unraid.

I added a book to the series and then removed it and it did clear that series yes. This originally occurred because I had the system automatically match the audiobooks which left me with a bunch of empty series.

**Comment by hornofabraxas** [comment]
Same here, 2.11 new install, had this issue with quick match, had to add book manually back to original series and run a regular Match to fix.

**Comment by Br33ce** [comment]
Same problem on v2.17.2 and same fixed worked..

**Comment by Br33ce** [comment]
Unfortunately this problem is apparent again with v2.17.2 and same fixed worked.. @advplyr

**Comment by advplyr** [comment]
I was able to reproduce the issue using the bulk quick match feature and Update Details enabled.

![image](https://github.com/user-attachments/assets/d792cc2a-a14b-4501-87d2-92432e0bea96)

That was the only way I was able to get an empty series. Did you use that method?

**Comment by advplyr** [comment]
Update. I was also able to reproduce the issue with "Prefer matched metadata" enable in settings.

**Comment by Br33ce** [comment]
Interesting enough I've just re checked and I do not have the prefer matched setting enabled but still got the empty series. I've enabled Update Covers as well.

**Comment by jallen810** [comment]
I can confirm I am having the same issue, running v2.17.5 on TrueNAS Scale. Any suggestions to resolve? Can we simply allow user to have a pencil ‘Edit’ button to allow us to hide (or delete)?

**Comment by nichwall** [comment]
I believe this was fixed in 2.17.6?

https://github.com/advplyr/audiobookshelf/releases/tag/v2.17.6

**Comment by advplyr** [comment]
Oh yeah thanks this is fixed

**Comment by jallen810** [comment]
Can confirm. Just figured out how to update on my end. running V2.17.7 now and the empty series are gone. Sorry if i freaked anyone out, still new the the env

**Comment by PhilippKammann** [comment]
![Image](https://github.com/user-attachments/assets/21bb7061-39c4-4dfd-94ce-c3dacbd0018a)
The issue still exists in v2.21.0

Adding the a book created the serie "00. Garro", I then deleted the book file and scanned. Audiobookshelf said the book was missing and I deleted the entry in the WebUI, but the series remained with 0 books
