### ISSUE TITLE
[Bug]: fetch rss feed content error 

### ISSUE THREAD

**Issue by Rookiewan** [advplyr/audiobookshelf#2446]
### Describe the issue

When I upgrade to version v2.7.0, I get an error when I click the search button. But in version v2.6.0 it was good
![image](https://github.com/advplyr/audiobookshelf/assets/13617296/514b2512-2478-4124-9d29-2af82c52ae20)

I compared the two versions of the error code, and I don't know which code is causing it
![image](https://github.com/advplyr/audiobookshelf/assets/13617296/24c536f5-14e9-45da-82b9-177b983fde60)

### Steps to reproduce the issue

1. add url http://www.ximalaya.com/album/51247350.xml
2. click search button

### Audiobookshelf version

v2.7.0

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.7.1](https://github.com/advplyr/audiobookshelf/releases/tag/v2.7.1)

**Comment by Ridgehiker8** [comment]
I am still getting this behavior for the rss feed http://cdn.thesecretcabal.com/scpodcast.xml.

I am using v2.7.1 through Docker.

**Comment by advplyr** [comment]
@Ridgehiker8 I fixed this again for the next release. This should hopefully be the final update since the accept header has wildcard now.
```
Accept: 'application/rss+xml, application/xhtml+xml, application/xml, */*;q=0.8'
```

**Comment by advplyr** [comment]
Fixed in https://github.com/advplyr/audiobookshelf/releases/tag/v2.7.2
