### ISSUE TITLE
[Bug]: EoC sleep timer doesn't reset for web

### ISSUE THREAD

**Issue by danielb2** [advplyr/audiobookshelf#4914]
### What happened?

this has caught me a number of times, but the End of Chapter sleep timer doesn't restart on the web version.

### What did you expect to happen?

I expected it to reset after setting it, and not just stop.  It would be best if this could be implemented like smart audiobook player. 

### Steps to reproduce the issue

1. open web version and play any book
2. set EoC sleep timer
3. have it run out
4. it doesn't reset

### Audiobookshelf version

v2.31.0

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

None

### Logs

```shell

```

### Additional Notes

note web version doesn't display version number anywhere. probably should.

**Comment by SomeoneBooks** [comment]
It would be a nice addition, I support it

**Comment by harlanluo** [comment]
I tested this functionality on the latest environment and the EoC timer resets correctly after triggering. It appears this has been resolved in recent updates.

**Comment by philipsteingruber** [comment]
Still happening for me on 2.36.0 (web/Chrome, Docker).

Doesn't even need a book switch to trigger it. Let EoC run out, then set EoC again on the same book, and it just stops playback instantly instead of starting a new countdown. Restarting playback and setting the timer again fixes it every time, first try.
