### ISSUE TITLE
[Bug]: Podcast empty for old User (Tag System)

### ISSUE THREAD

**Issue by skyzuma** [advplyr/audiobookshelf#542]
### Describe the issue

for old / existing user - except root - the podcast homepage is empty but if i create a new user (guest/user) the podcast home is available and filed ...

### Steps to reproduce the issue

1. idk but create an user with an old image like 1.X and update to 2.X ?

### Audiobookshelf version

v2.0.8

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Please check logs

**Comment by skyzuma** [comment]
container logs? there is no info ... only connect / disconnect

**Comment by skyzuma** [comment]
ive found the "Problem" ... the tag system ... if i allow not all tags > user have empty podcast homepage ... and there is a weird things ... if i deactivate and activate "Can Access All Tags" there are a weird tag? first is "main" and second is "lib_xxxxxxxxxxxxxxxxxx" (podcast homepage also empty) ... idk what this is > delete this tags and select an existing one > user has access to this books with this tag(s) but the podcast homepage is empty >>> if "Can Access All Tags" deactivated > user can show the podcasts ...

**Comment by advplyr** [comment]
Yes I can see it also. That is a bug with tags, thanks.

**Comment by advplyr** [comment]
Will be fixed in the next release.

**Comment by advplyr** [comment]
Fixed in [v2.0.9](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.9)

**Comment by skyzuma** [comment]
is not fixed :( if i deactivate "Can Access All Tags" and select any tags (the field is empty unlike v 2.0.8) > user can see and read the tagged books but the podcast homepage is still empty ... activate "Can Access All Tags" > users podcast homepage is filled ... i have only 1 podcast with 2 episodes, idk if this the problem

> if i deactivate "Can Access All Tags" there are a weird tag? first is "main" and second is "lib_xxxxxxxxxxxxxxxxxx"

**lib_X** is the name of the podcast link: ip/library/**lib_X**/bookshelf ... but if i deactivate "Can Access All Libraries" there is "name of the main library" and Podcast (not lib_X)

> Can Access All Tags

if i search for anything on the main library and switch to the second (podcast)/library > no results for xxx (search from main library) ... cause there is an active research from the main library

**Comment by advplyr** [comment]
I just tested and this is working as expected. This may be a misunderstanding of the feature.

Here is what I did to test:
1. Go into my podcast library and add a tag "test" to a podcast.
2. Go into my main library and add a tag "test" to an audiobook.
3. Create a new account and disable access all tags and select the tag "test"
4. Login to the new account and see the 1 podcast with tag "test" and the 1 audiobook.

**Comment by skyzuma** [comment]
i think this is completely misunderstanding of all ... i have 2 libs ... main and podcast ... the user have: "Can Access All Libraries = yes" / "Can Access All Tags = no > Tags Accessible to User: tag1, tag2 for main"

main = i have many tags
podcast = i have no tags

user login:

main > access all tags for main from settings above [tag1, tag2 ]
podcast > Home / Library > Podcast Library is empty!

user > "Can Access All Tags = yes" > user can see all podcasts ...

i dont use, need tags on podcast ... the system forces me to use podcast tags ...

and yes, if i give the podcast an tag, i can use it in the settings in "Tags Accessible to User" ... 

the problem is, IF NO TAG on any podcast, the system gives no access to any podcast and set an tag to an podcast, i can see only the tagged podcast ... so i need to tag ALL podcasts ...

maybe we need an extra "Tags Accessible to User" for podcast ... now all tags habe one "system" > Tags Accessible to User (for main AND podcast) ... i thinks its the same for and 3rd or 4th lib too ...

**Comment by advplyr** [comment]
I understand. I think adding tag level permissions for each library could be more complex then we need to go. I'm not sure how this would look like in the GUI but if you come up with a design that you think could work I'm open to building it out.

I think we will be adding another permission which will be restricting based on genre.
