### ISSUE TITLE
"Failed to get podcast feed" from patreon private RSS podcast feed.

### ISSUE THREAD

**Issue by silentArtifact** [advplyr/audiobookshelf#634]
I'm a patreon subscriber for a podcast (Old Gods of Appalachia, if it matters), and I'd love to be able to pull episodes, but for whatever reason Audiobookshelf throws a "Failed to get podcast feed" from the RSS link provided by Patreon. Running on Docker, on a Synology NAS, most recent version.

**Comment by advplyr** [comment]
Are you able to add the podcast? Where are you getting this error?

**Comment by silentArtifact** [comment]
Yeah, I'm able to add it, no problem there, and it even pulls an image and a brief description, but when I click "Find Episodes" a red notice slides in on the top-right saying "Failed to get podcast feed". If it'll help, I can send you the feed URL?

**Comment by advplyr** [comment]
Fixed in [v2.0.18](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.18)

**Comment by silentArtifact** [comment]
I'm still getting this error, unfortunately. I can send you the feed, if that would help, or logs or whatnot?

**Comment by advplyr** [comment]
You will need to remove the podcast and re-add it.

**Comment by Fabaderheld** [comment]
I experience it with 2.0.20 as well. 
I can reproduce it be forcing a re-scan, the RSS URL changes from
```https://www.patreon.com/rss/stayforever?auth=xxxxxx```
to
```https://www.patreon.com/rss/stayforever?auth=```

anybody else experience this ?

thanks

Faba

**Comment by advplyr** [comment]
@Fabaderheld Are you storing an `.abs` file inside the podcast folder? If so, it is taking precedence over everything else so double check the feedUrl saved there.
If that `.abs` file was created before that fix was pushed in v2.0.18 then that would make sense

**Comment by Fabaderheld** [comment]
Indeed there was an .abs file for the podcasts folder. 

I tried deleting it and it was recreated, with the wrong URL. The I edited the file with correct URL

```
;ABMETADATA2
#audiobookshelf v2.0.20

media=podcast
title=Stay Forever: Der geheime Patreon-Feed!
author=Stay Forever: Der geheime Patreon-Feed!
language=
genres=
feedUrl=https://www.patreon.com/rss/stayforever?auth=xxxxxxxx
itunesId=
explicit=N

[DESCRIPTION]
Stay Forever's Private RSS Feed for Fabian Sasse
```

Afterwards I did "Force Re-Scan" but still the URL was wrong and the .abs file was updated with the wrong URL

```
;ABMETADATA2
#audiobookshelf v2.0.20

media=podcast
title=Stay Forever: Der geheime Patreon-Feed!
author=Stay Forever: Der geheime Patreon-Feed!
language=
genres=
feedUrl=https://www.patreon.com/rss/stayforever?auth
itunesId=
explicit=N

[DESCRIPTION]
Stay Forever's Private RSS Feed for Fabian Sasse
```

If there is anything else to test let me know.

regards

Fabian

**Comment by Fabaderheld** [comment]
Another thing I tried was deleting the podcast and remove also all files on disk and the re-adding it. Unfortunately with the same result.

**Comment by advplyr** [comment]
I found what was going on here, will be fixed in the next release.

**Comment by spidermatt99** [comment]
I continue to get this error message when trying to add a private feed for Stratechery, using the stratechery.passport.online domain. It had worked in a previous version, I think, but it stopped syncing and after deleting and trying to re-add it, it seems it can no longer read the RSS feed for some reason. It loads fine in a browser and in other apps.
