### ISSUE TITLE
[Bug]: Library filter for Finished does not work

### ISSUE THREAD

**Issue by jmt-gh** [advplyr/audiobookshelf#704]
### Describe the issue

Applying the finished filter in the library view results in showing nothing

```
[2022-06-08T04:40:50.659Z] DEBUG: [DB] Updated user: 1 | Selected: 1
TypeError: Cannot read properties of undefined (reading 'isFinished')
    at /git/audiobookshelf/server/utils/libraryHelpers.js:35:75
    at Array.filter (<anonymous>)
    at Object.getFilteredLibraryItems (git/audiobookshelf/server/utils/libraryHelpers.js:31:29)
    at ApiRouter.getLibraryItems git/audiobookshelf/server/controllers/LibraryController.js:166:37)
    at Layer.handle [as handle_request] (git/audiobookshelf/node_modules/express/lib/router/layer.js:95:5)
    at next (git/audiobookshelf/node_modules/express/lib/router/route.js:144:13)
    at ApiRouter.middleware (git/audiobookshelf/server/controllers/LibraryController.js:501:5)
    at Layer.handle [as handle_request] (git/audiobookshelf/node_modules/express/lib/router/layer.js:95:5)
    at next (git/audiobookshelf/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (0git/audiobookshelf/node_modules/express/lib/router/route.js:114:3)
```

### Steps to reproduce the issue

1. set finshed on a book
2. go to library view
3. filter for finished

### Audiobookshelf version

v2.0.19

### How are you running audiobookshelf?

Docker

**Comment by jmt-gh** [comment]
the offending commit:

https://github.com/advplyr/audiobookshelf/commit/0d1ff35c5ec05bcb73cd6fbf43abe8df062e397e

**Comment by jmt-gh** [comment]
Didn't realize this was fixed here. woops

https://github.com/advplyr/audiobookshelf/commit/881baa818d483055b632269ff485e1f14aed5749

**Comment by DieselTech** [comment]
This bug is still around in v2.0.20

```
TypeError: Cannot read properties of undefined (reading 'isFinished')
    at /server/utils/libraryHelpers.js:35:75
    at Array.filter (<anonymous>)
    at Object.getFilteredLibraryItems (/server/utils/libraryHelpers.js:31:29)
    at ApiRouter.getLibraryItems (/server/controllers/LibraryController.js:166:37)
    at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
    at next (/node_modules/express/lib/router/route.js:144:13)
    at ApiRouter.middleware (/server/controllers/LibraryController.js:501:5)
    at Route.dispatch (/node_modules/express/lib/router/route.js:114:3)
```

It's also hard to "find" the logs because they aren't being written to files as per #706

**Comment by advplyr** [comment]
That bug was fixed after the 2.0.20 release, so will be in 2.0.21
