### ISSUE TITLE
BUG: (Nasty one) Backup created a 25+GB file

### ISSUE THREAD

**Issue by Kudjo-Grand** [advplyr/audiobookshelf#92]
I'm not sure this was supposed to do this. I thought I read somewhere that it is supposed to stop after 1GB?

![image](https://user-images.githubusercontent.com/25695143/136772084-cd8034ff-9f01-48ec-826f-d6bb5d57bf21.png)

Am I remembering wrong? 

What do you think?

**Comment by scorpio862** [comment]
I had exactly the same problem because I had the /config directory from container mapped as a main audiobookshelf forlder in unraid appdata. 

I fixed it by by creating a "config" folder in the main audiobookshelf folder and moving all folders except for metadata to this new config folder and I reconfigured the docker config so it looks like this:

![image](https://user-images.githubusercontent.com/50056988/137174603-c331127e-787d-43bd-963c-67b54908ac44.png)

The problem is with the default configuration, when you instal Audiobookshelf in unraid as it mounts /medatada in /config.
It looks like this:

![image](https://user-images.githubusercontent.com/50056988/137176367-b819da5c-d5a2-45c0-abf6-702ceb6ca51e.png)


This way if you make the Backup, it backs up everything in the metadata folder, including previous backups and the file sizes are huge.
The container's default configuration needs changing so new users don't have this problem.

**Comment by advplyr** [comment]
I figured out why that was happening and responded [here](https://github.com/advplyr/audiobookshelf/issues/89#issuecomment-943393190)

I'm still not sure why the 1GB is not honored, but also the backup trying to continually zip itself will probably have unexpected behavior. The solution I used was to only zip the 4 directories used for the DB inside the `/config` directory, as opposed to zipping the entire directory.
This is still not ideal since I designed it thinking those directories would be separate, so I think another revision of this will be needed down the road.
